### ISSUE TITLE
Tracking issue for CB3 migration

### ISSUE THREAD

**Issue by jaimergp** [omnia-md/conda-dev-recipes#181]
I am taking over the excellent work @Lnaden started in this other PR #177 

# Pending issues

- [x] OpenMM does not build - fixed in #180 
- [x] Add the BINSTAR Token to the Azure org to handle uploads - fixed in #180 
- [ ] Make sure we are uploading to the correct channel/label
- [ ] Linux: mount repo to `$HOME` instead of `/io` so we get the `conda_build_config.yaml` pinnings.
- [ ] Update README with new changes
- [ ] Build OpenMM docs. Shall we create a separate package `openmm-docs`?

# Further work and ideas

- [ ] Figure out how to unify recipes for main / beta / nightly builds
- [ ] Idea: Investigate improved CF compatibility through `conda-forge-pinning` compatibility
- [ ] Idea: `openmm-docs` can be created as a separate package, simplifying the Docker images and reducing build time.
- [ ] PowerPC builds should be possible too once the CF PPC Docker images are available ([WIP](https://github.com/conda-forge/docker-images/pull/113)).

# Changelog

* 2020.01.17. Nightly uploads _should_ work now after #182 
* 2020.01.14. Docker images are now living in `omnia-md/cf-docker` images and being uploaded to `omniamd/linux-anvil-cuda` in Docker Hub. In principle, everything is setup for tonight's nightly build, which should result in uploads to `omnia-dev`.
* 2020.01.13. Docker images with TeXLive had an issue with `glibc` that resulted in core dumps at install time for OpenMM. They have been replaced with the Conda Forge CUDA images, augmented with more CUDA versions (8.0, 9.0, 9.1). The fork resides in https://github.com/jaimergp/cf-docker-images. They have recently added `ppc64le` support for their CUDA images so we could build those too.
